### PR TITLE
New approach to server start.

### PR DESCRIPTION
**Pull request by jsosniakk**
Please @mptak12 review this change to new server start.

Now you can start server without /app added in URL bar.

image

### CODE REVIEW

**Review by TheDukato — APPROVED** [review]
Form my perspective is correct

**Review by mptak12 — APPROVED** [review]
Looks good

**Review by BartoszKowal — APPROVED** [review]

**Review by BartoszJatczyszyn — COMMENTED** [review]
good

**Comment by kaszubam9** [comment]
+

**Review by BartoszJatczyszyn — APPROVED** [review]

**Comment by kaszubam9** [comment]
dsadsa

**Review by kaszubam9 — APPROVED** [review]
\+

**Pull request merged**
